### ISSUE TITLE
Support initial state

### ISSUE THREAD

**Issue by naorye** [redux-utilities/reduce-reducers#9]
Currently the code doesn't support initial state for the second reducer.
What do you think about the following solutions?

```
export function reduceReducers(...reducers) {
    return (state, action) => {
        let isInitial = !state;
        return reducers.reduce((newState, reducer) => {
            if (isInitial) {
                return { ...newState, ...reducer(undefined, action) };
            } else {
                return reducer(newState, action);
            }
        }, { ...state });
    };
}
```

or

```
export function reduceReducers(initialState, ...reducers) {
    return (state, action) => {
        let isInitial = !state;
        return reducers.reduce((newState, reducer) => {
            return reducer(newState, action);
        }, isInitial ? initialState : { ...state });
    };
}
```

**Comment by tricoder42** [comment]
First, `isInitial` should strictly check that `state` is `undefined`, because state might contain falsy values (false, 0, "").

Second, this code assumes that reducer returns an object. There're plenty of use cases when reducer returns boolean or number instead.

Last, even if reducer returns an object, it should only add props missing from `newState`, not override them:

```
// change order of reducer(...) and newState
return { ...reducer(undefined, action), ...newState };
```

---

Huh, I thought that this should be an easy picking, but it's actually pretty complicated. My other concerns are if this is responsibility of `reduceReducers` or reducers itself. We're expecting some behavior we're used to from `combineReducers`. On the other hand, it's very inconvenient to check for uninitialized values on every call, so there's should be probably some compromise.

**Comment by lutangar** [comment]
I packaged something close to @naorye first implementation along with @tricoder42 suggestions there [reduce-merge-reducers](https://github.com/lutangar/reduce-merge-reducers).
However I couldn't find a way to detect (and throw) if one of the reducer `initialState` is not a plain object. Any ideas?

**Comment by EricFries** [comment]
This thread has been really helpful in a project I'm working on so thanks for your work here!   I want to ensure that the `initialState` of the _last_ reducer passed into the reduce function is maintained in the event of a conflict with a prior reducer's `initialState`.

I noticed a slight difference in the handling of state when `isInitial` is `true` between @lutangar 's package: 
`return { ...r(undefined, current), ...p };`

and @naorye 's first example:
`return { ...newState, ...reducer(undefined, action) };`

If I understand correctly, if there are conflicting keys between the `newState` (or `p`)  and the return value of the reducer function, this difference affects which overrides which due to the ordering of the destructuring.  

Besides determining which reducer's state overrides which, is there any other reason to do one over the other?

**Comment by canercandan** [comment]
A simpler way to accomplish this is with a dummy first reducer that returns an initial state if state is undefined otherwise the state as it is:

```js
const initialState = Immutable.fromJS({
  a: 0,
});

reduceReducers(
  (state) => state || initialState,
  (state, action) => state.update('a', x => x + 21),
  (state, action) => state.update('a', x => x * 2)
)().toJS() // displays {a: 42}
```

**Comment by timche** [comment]
I've opened #13 to work at this feature and made a proposal. Please take a look at it and give your feedback. I hope that I understood the problem correctly.
